version: '3.8'

services:
  db_postgres:
    image: postgres:13.0
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: Hello1!
      POSTGRES_DB: waterer_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: proxy
    ports:
      - '80:5000' # expose 80 on host and sent to 5000 in container
    secrets:
      - aws_credentials
      - phone_number
    volumes:
      - type: bind
        source: .
        target: /var/www
    working_dir:
      /var/www
    entrypoint:
      python
    command:
      wsgi.py
volumes:
  postgres-data:
secrets:
   aws_credentials:
     file: accessKeys.csv
   phone_number:
     file: PhoneNumber.txt
